BAS/urls.py
import os

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('',ArticleListView.as_view(),name='home'),
    path('admin/', admin.site.urls),
    path('accounts/',include('accountapp.urls')),
    path('profiles/',include('profileapp.urls')),
    path('articles/',include('articleapp.urls')),
    path('comments/',include('commentapp.urls')),
    path('projects/',include('projectapp.urls')),
    path('subscribe/',include('subscriptionapp.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include, reverse_lazy

from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'

urlpatterns = [
    path('login/',LoginView.as_view(template_name='accountapp/login.html'),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('create/',AccountCreateView.as_view(),name='create'),
    path('mypage/<int:pk>',AccountDetailView.as_view(),name='detail'),
    path('change/<int:pk>',AccountUpdateView.as_view(),name='update'),
    path('quit/<int:pk>',AccountDeleteView.as_view(),name='delete'),
]

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns = [
    path('',ProfileCreateView.as_view(),name='create'),
    path('update/<int:pk>',ProfileUpdateView.as_view(),name='update')
]

accountapp/models.py
from django.db import models

# Create your models here.

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from projectapp.models import Project


class Article(models.Model):
    wrtier = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,related_name='article')
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, null=True, related_name='article')
    title = models.CharField(max_length=200, null=True)
    content = models.TextField(null=True)
    image = models.ImageField(upload_to='article/',null=False)
    created_at = models.DateField(auto_now_add=True,null=True)

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm

class UserUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].disabled = True

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden

# Create your views here.
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.views.generic.list import MultipleObjectMixin

from accountapp.decorators import account_ownership_required
from accountapp.forms import UserUpdateForm
from articleapp.models import Article

has_ownership = [account_ownership_required, login_required]

class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('home')
    template_name = 'accountapp/create.html'


class AccountDetailView(DetailView,MultipleObjectMixin):
    model = User
    context_object_name = 'target_user'
    template_name =  'accountapp/detail.html'

    paginate_by = 10

    def get_context_data(self, **kwargs):
        # project = self.object
        object_list = Article.objects.filter(wrtier=self.get_object())

        return super(AccountDetailView,self).get_context_data(object_list=object_list,**kwargs)



@method_decorator(has_ownership,'get')
@method_decorator(has_ownership,'post')
class AccountUpdateView(UpdateView):
    model = User
    context_object_name = 'target_user'
    form_class = UserUpdateForm
    success_url = reverse_lazy('home')
    template_name = 'accountapp/update.html'


@method_decorator(has_ownership,'get')
@method_decorator(has_ownership,'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('home')
    template_name = 'accountapp/delete.html'

accountapp/templates/accountapp/create.html
{% extends 'index.html' %}}
{% load bootstrap4 %}

{% block body %}


    <h3 style="text-align:center;">SignUP</h3>
    <div style="width: 400px; margin: 2rem auto;">
        <form style="text-align:center;" action="{% url 'accountapp:create' %}" method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-secondary rounded-pill col-6 mt-3" value="SUBMIT">
        </form>
    </div>
{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'index.html' %}}
{% load bootstrap4 %}

{% block body %}
    <h3 style="text-align:center;">Delete Account</h3>
    <div style="width: 400px; margin: 2rem auto;">
      <div style="width: 400px; margin: 0 auto; font-size:2.5rem;">
            {{ target_user.username }}
        </div>
        <div>
            {{ target_user.date_joined }}
        </div>
        <form style="text-align:center;" action="{% url 'accountapp:delete' pk=target_user.pk %}" method="POST">
            {% csrf_token %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3" value="QUIT">
        </form>
    </div>
{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'index.html' %}}
{% load bootstrap4 %}

{% block body %}

    <div style="text-align:center;">
        <h3>My Page</h3>
        <div>
            {% if target_user.profile %}
            <figure><img style="width: 150px; height: 150px; border-radius:50%;"src="{{ target_user.profile.image.url }}" alt=""></figure>
            <h5>{{ target_user.profile.nickname }}</h5>
            <div>{{ target_user.profile.message }}</div>
                {% if target_user == user %}
                <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}">Edit Profile</a>
                <div><a href="{% url 'accountapp:update' pk=target_user.pk %}" class="btn btn-primary
                rounded-pill col-3 mt-3">Change Info</a>
                <a href="{% url 'accountapp:delete' pk=target_user.pk %}" ><input class="btn btn-secondary
                rounded-pill col-2 mt-3" type="button"value="QUIT"></a></div>
                {% endif %}
            {% else %}
            <div style="width: 400px; margin: 0 auto; font-size:2.5rem;">
                <h3 style="color: red;"><em>Create Profile Please.</em></h3>
            </div>
                {% if target_user == user %}
                <a href="{% url 'profileapp:create' %}">Create Profile</a>

                {% endif %}

            {% endif %}
            <hr>
            <div>
                {% include 'snippets/list_Fragment.html' with article_list=object_list %}
            </div>
        </div>



    </div>

{% endblock %}

accountapp/templates/accountapp/home.html
{% extends 'index.html' %}

{% block body %}
    <div>
        <form action="/accounts/" method="POST">
            {% csrf_token %}
            <input type="text" placeholder="comment Hello!" name="input_text">
            <input type="submit" class="btn btn-secondary col-1" value="SUBMIT">
        </form>
    </div>
    {% if text %}
        {% for data in text %}
        <div>{{data.text}}</div>
        {% endfor %}
    {% endif %}
{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'index.html' %}}
{% load bootstrap4 %}

{% block body %}

    {% csrf_token %}
    <h3 style="text-align:center;">Login</h3>
    <div style="width: 400px; margin: 2rem auto;">
        <form style="text-align:center;"  method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-secondary rounded-pill col-6 mt-3" value="SUBMIT">
        </form>
    </div>
{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'index.html' %}}
{% load bootstrap4 %}

{% block body %}
    <h3 style="text-align:center;">Change Info</h3>
    <div style="width: 400px; margin: 2rem auto;">
        <form style="text-align:center;" action="{% url 'accountapp:update' pk=target_user.pk %}" method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-secondary rounded-pill col-6 mt-3" value="SUBMIT">
        </form>
    </div>
{% endblock %}