BAS/urls.py
import os

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('',ArticleListView.as_view(),name='home'),
    path('admin/', admin.site.urls),
    path('accounts/',include('accountapp.urls')),
    path('profiles/',include('profileapp.urls')),
    path('articles/',include('articleapp.urls')),
    path('comments/',include('commentapp.urls')),
    path('projects/',include('projectapp.urls')),
    path('subscribe/',include('subscriptionapp.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('',ArticleListView.as_view(),name='list'),
    path('create/',ArticleCreateView.as_view(),name='create'),
    path('detail/<int:pk>',ArticleDetailView.as_view(),name='detail'),
    path('update/<int:pk>',ArticleUpdateView.as_view(),name='update'),
    path('delete/<int:pk>',ArticleDeleteView.as_view(),name='delete')
]

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from projectapp.models import Project


class Article(models.Model):
    wrtier = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,related_name='article')
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, null=True, related_name='article')
    title = models.CharField(max_length=200, null=True)
    content = models.TextField(null=True)
    image = models.ImageField(upload_to='article/',null=False)
    created_at = models.DateField(auto_now_add=True,null=True)

templates/snippets/card.html
<div>
    <img src="{{ article.image.url }}">
</div>

templates/snippets/list_Fragment.html
{% load static %}

{% block body %}
<style>

    .container div {
    width: 250px;
    background-color: antiquewhite;
    display: flex;
    justify-content: center;
    align-items: center;
    border-radius: 1rem;
  }

    .container img {
    width: 100%;
    border-radius: 1rem;
    }

</style>
  {% if article_list %}
  <div class="container">
      {% for article in article_list %}
        <a href="{% url 'articleapp:detail' pk=article.pk %}">
          {% include 'snippets/card.html' with article=article%}
        </a>
      {% endfor %}
  </div>
  <script src="{% static 'js/Mgic_Grid.js' %}"></script>
  {% else %}
<div style="text-align:center;"><h4>Your Article is None YET!</h4></div>
  {% endif %}
  {% include 'snippets/pagination.html' with page_obj=page_obj %}


  <div style="text-align:center;">
    <a href="{% url 'articleapp:create' %}" class="btn btn-dark rounded-pill col-3 mt-3" >
      Upload Article</a>
  </div>

{% endblock %}

templates/snippets/pagination.html
<div style="text-align:center; margin: 1rem 0;">
  {% if page_obj.has_previous %}
  <a href="{% url 'articleapp:list' %}?page={{ page_obj.previous_page_number }}"
     class="btn btn-secondary rounded-pill">
   {{page_obj.previous_page_number}}
  </a>
  {% endif %}

  <a href="?page={{ page_obj.number }}" class="btn btn-secondary rounded-pill active">
   {{page_obj.number}}
  </a>

  {% if page_obj.has_next %}
  <a href="?page={{ page_obj.next_page_number }}" class="btn btn-secondary rounded-pill">
   {{page_obj.next_page_number}}
  </a>
  {% endif %}
</div>

templates/snippets/square.html
<div>
    <img src="{{ project.image.url }}">
    <div>{{project.title | truncatechars:10 }}</div>
</div>