BAS/urls.py
import os

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('',ArticleListView.as_view(),name='home'),
    path('admin/', admin.site.urls),
    path('accounts/',include('accountapp.urls')),
    path('profiles/',include('profileapp.urls')),
    path('articles/',include('articleapp.urls')),
    path('comments/',include('commentapp.urls')),
    path('projects/',include('projectapp.urls')),
    path('subscribe/',include('subscriptionapp.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectCreateView, ProjectDetailView, ProjectListView

app_name = 'projectapp'

urlpatterns = [
    path('',ProjectListView.as_view(),name='list'),
    path('create/',ProjectCreateView.as_view(),name='create'),
    path('detail/<int:pk>',ProjectDetailView.as_view(),name='detail'),
]

subscriptionapp/urls.py
from django.urls import path

from subscriptionapp.views import SubscribeView, SubscribeListView

app_name = 'subscriptionapp'

urlpatterns = [
    path('',SubscribeView.as_view(),name='subscribe'),
    path('list/',SubscribeListView.as_view(),name='list')
]

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from projectapp.models import Project


class Article(models.Model):
    wrtier = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,related_name='article')
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, null=True, related_name='article')
    title = models.CharField(max_length=200, null=True)
    content = models.TextField(null=True)
    image = models.ImageField(upload_to='article/',null=False)
    created_at = models.DateField(auto_now_add=True,null=True)

projectapp/models.py
from django.db import models

# Create your models here.

class Project(models.Model):
    title = models.CharField(max_length=20, null=False)
    image = models.ImageField(upload_to='project/', null=True)
    description = models.TextField(null=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'${self.title}'

projectapp/forms.py
from django.forms import ModelForm

from projectapp.models import Project


class ProjectCreationForm(ModelForm):
    class Meta:
        model = Project
        fields = ['image','title','description']

projectapp/views.py
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, DetailView, ListView
from django.views.generic.list import MultipleObjectMixin

from articleapp.models import Article
from projectapp.forms import ProjectCreationForm
from projectapp.models import Project
from subscriptionapp.models import Subscribe


class ProjectCreateView(CreateView):
    model = Project
    form_class = ProjectCreationForm
    template_name = 'projectapp/create.html'

    def get_success_url(self):
        return reverse('projectapp:detail',kwargs={'pk':self.object.pk})

class ProjectDetailView(DetailView,MultipleObjectMixin):
    model = Project
    context_object_name = 'target_project'
    template_name = 'projectapp/detail.html'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        project = self.object
        user = self.request.user

        if user.is_authenticated:
            subscription = Subscribe.objects.filter(project=project, user=user)
        else:
            subscription = None

        object_list = Article.objects.filter(project=self.get_object())

        return super(ProjectDetailView,self).get_context_data(object_list=object_list,subscription=subscription,**kwargs)

class ProjectListView(ListView):
    model = Project
    context_object_name = 'project_list'
    template_name = 'projectapp/list.html'
    paginate_by = 20

projectapp/templates/projectapp/create.html
{% extends 'index.html' %}}
{% load bootstrap4 %}

{% block body %}

    <h3 style="text-align:center;">Create Your Project</h3>
    <div style="width: 400px; margin: 2rem auto;">
        <form style="text-align:center;" action="{% url 'projectapp:create' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-secondary rounded-pill col-6 mt-3" value="SUBMIT">
        </form>
    </div>
{% endblock %}

projectapp/templates/projectapp/detail.html
{% extends 'index.html' %}}
{% load bootstrap4 %}

{% block body %}
    <div style="text-align:center;">
        <div>
            <h2>{{ target_project.title }}</h2>
            <figure><img style="width: 100%; border-radius:1rem;"src="{{ target_project.image.url }}" alt=""></figure>
            <div>{{ target_project.description }}</div>
        </div>
    <hr>
        {% if not subscription %}
            <div><a class="btn btn-dark rounded-pill col-3 mt-3" href="{% url 'subscriptionapp:subscribe' %}?project_pk={{target_project.pk}}">Subscribe</a></div>
        {% else %}
            <div><a class="btn btn-dark rounded-pill col-3 mt-3" href="{% url 'subscriptionapp:subscribe' %}?project_pk={{target_project.pk}}">Unsubscribe</a></div>
        {% endif %}
        <div>
             {% include 'snippets/list_Fragment.html' with article_list=object_list %}
        </div>
        </div>
{% endblock %}

projectapp/templates/projectapp/list.html
{% extends 'index.html' %}}
{% load static %}

{% block body %}
<style>

    .container div {
    width: 250px;
    background-color: antiquewhite;
    display: flex;
    justify-content: center;
    align-items: center;
    border-radius: 1rem;
  }

    .container img {
    width: 100%;
    border-radius: 1rem;
    }

</style>
  {% if project_list %}
  <div class="container">
      {% for project in project_list %}
        <a href="{% url 'projectapp:detail' pk=project.pk %}">
          {% include 'snippets/square.html' with project=project %}
        </a>
      {% endfor %}
  </div>
  <script src="{% static 'js/Mgic_Grid.js' %}"></script>
  {% else %}
<div style="text-align:center;"><h4>Your Project is None YET!</h4></div>
  {% endif %}
  {% include 'snippets/pagination.html' with page_obj=page_obj %}


  <div style="text-align:center;">
    <a href="{% url 'projectapp:create' %}" class="btn btn-dark rounded-pill col-3 mt-3" >
      Create Project</a>
  </div>

{% endblock %}