BAS/urls.py
import os

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('',ArticleListView.as_view(),name='home'),
    path('admin/', admin.site.urls),
    path('accounts/',include('accountapp.urls')),
    path('profiles/',include('profileapp.urls')),
    path('articles/',include('articleapp.urls')),
    path('comments/',include('commentapp.urls')),
    path('projects/',include('projectapp.urls')),
    path('subscribe/',include('subscriptionapp.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include, reverse_lazy

from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'

urlpatterns = [
    path('login/',LoginView.as_view(template_name='accountapp/login.html'),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('create/',AccountCreateView.as_view(),name='create'),
    path('mypage/<int:pk>',AccountDetailView.as_view(),name='detail'),
    path('change/<int:pk>',AccountUpdateView.as_view(),name='update'),
    path('quit/<int:pk>',AccountDeleteView.as_view(),name='delete'),
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('',ArticleListView.as_view(),name='list'),
    path('create/',ArticleCreateView.as_view(),name='create'),
    path('detail/<int:pk>',ArticleDetailView.as_view(),name='detail'),
    path('update/<int:pk>',ArticleUpdateView.as_view(),name='update'),
    path('delete/<int:pk>',ArticleDeleteView.as_view(),name='delete')
]

projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectCreateView, ProjectDetailView, ProjectListView

app_name = 'projectapp'

urlpatterns = [
    path('',ProjectListView.as_view(),name='list'),
    path('create/',ProjectCreateView.as_view(),name='create'),
    path('detail/<int:pk>',ProjectDetailView.as_view(),name='detail'),
]

subscriptionapp/urls.py
from django.urls import path

from subscriptionapp.views import SubscribeView, SubscribeListView

app_name = 'subscriptionapp'

urlpatterns = [
    path('',SubscribeView.as_view(),name='subscribe'),
    path('list/',SubscribeListView.as_view(),name='list')
]

templates/footer.html
<footer class="footer">
    <span>NOTICE</span> |
    <span>ABOUT</span> |
    <span>CONTACT</span> |
    <span>SNS</span>
    <h3 class="footer-logo">BAS</h3>
</footer>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <title>BAS</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Baloo+Tammudu+2&display=swap" rel="stylesheet">
    <link href="{% static 'css.css' %}" type="text/css" rel="stylesheet">
</head>

templates/header.html
<header class="header">
    <h1 class="header-logo"><a href="{% url 'home'%}">BarcodeStation</a></h1>
    <a href="{% url 'articleapp:list' %}"><span>Article</span></a> |
    <a href="{% url 'projectapp:list' %}"><span>Project</span></a> |
    <a href="{% url 'subscriptionapp:list' %}"><span>Subscribe</span></a> |
    {% if not user.is_authenticated %}
        <a href="{% url 'accountapp:login' %}?next={{request.path}}"><span>Login</span></a> |
        <a href="{% url 'accountapp:create' %}"><span>SignUp</span></a>
    {% else %}
        <a href="{% url 'accountapp:logout' %}?next={{request.path}}"><span>Logout</span></a> |
        <a href="{% url 'accountapp:detail' pk=user.pk %}"><span>MyPage</span></a>
    {% endif %}

</header>

templates/index.html
<!DOCTYPE html>
<html>
{% include 'head.html' %}
<body>
    {% include 'header.html' %}
    <hr>
    {% block body %}
    {% endblock %}
    <hr>
    {% include 'footer.html' %}
</body>
</html>